services:
  # Frontend / Web Server
  frontend:
    container_name: amazoniaviva-frontend
    build:                             
      context: ./frontend_project   
      dockerfile: Dockerfile
    image: patrick190/amazoniaviva_frontend:latest
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - proxy-network
    restart: always

  # Django Application (Backend)
  backend:
    container_name: amazoniaviva-backend
    build:
      context: .
      dockerfile: amazoniaviva/Dockerfile
    image: patrick190/amazoniaviva_backend:latest
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    env_file:
      - .env
    ports:
      - "8000:8000"
    # Si decides usar la base de datos local SQLite o mapear variables como volumen en el futuro:
    # volumes:
    #   - ./.env:/app/.env
    #   - amazoniaviva_db_data:/app/db_data
    networks:
      - proxy-network
    restart: always

  db:
    image: postgres:15-alpine
    container_name: amazoniaviva_db
    restart:  always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxy-network

  # Opcional: Database (si en algún momento decides migrar de SQLite a MySQL/PostgreSQL como en tu ejemplo)
  # db:
  #   container_name: amazoniaviva-mysql
  #   image: mysql:8.0
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #       reservations:
  #         memory: 512M
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_USER: ${DB_USERNAME}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - amazoniaviva_db_data:/var/lib/mysql
  #   networks:
  #     - amazoniaviva-network

networks:
  amazoniaviva-network:
    driver: bridge
  proxy-network:
    external: true
  

volumes:
  postgres_data: