# Generated by Django 6.0.2 on 2026-03-19 20:57

import cloudinary.models
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('caracteristicas', models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_identidad', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('autenticacion.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='logitid',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Actividad')),
                ('nivel_riesgo', models.PositiveSmallIntegerField(help_text='Escala del 1 (Mínimo) al 10 (Extremo)', verbose_name='Nivel de Riesgo (1-10)')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='autenticacion.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Tour')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (COP)')),
                ('duracion', models.CharField(max_length=100, verbose_name='Duración')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad Máxima')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación (Texto)')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('itinerario', models.JSONField(default=list, help_text="Formato esperado: [{'time': '08:00', 'activity': 'Salida'}]", verbose_name='Itinerario Detallado')),
                ('incluido', models.JSONField(default=list, help_text="Formato esperado: [{'item': 'Transporte'}]", verbose_name='Qué incluye')),
                ('rating', models.DecimalField(decimal_places=100, max_digits=100)),
                ('actividades', models.ManyToManyField(related_name='paquetes', to='autenticacion.actividad', verbose_name='Actividades Incluidas')),
            ],
            options={
                'verbose_name': 'Paquete Turístico',
                'verbose_name_plural': 'Paquetes Turísticos',
            },
        ),
        migrations.CreateModel(
            name='DestinoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('es_portada', models.BooleanField(default=False)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen_paquete', to='autenticacion.paqueteturistico')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('sku', models.CharField(max_length=150)),
                ('caracterisitcas', models.JSONField(blank=True, default=dict)),
                ('imagenes', models.JSONField(default=dict, null=True)),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('disponible', models.BooleanField()),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_categorias', to='autenticacion.categorias')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_proveedor', to='autenticacion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_carrito', to='autenticacion.carrito')),
                ('paquetes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_paquetes', to='autenticacion.paqueteturistico')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_productos', to='autenticacion.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorito_usuario', to=settings.AUTH_USER_MODEL)),
                ('paquetes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorito_paquetes', to='autenticacion.paqueteturistico')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorito_productos', to='autenticacion.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('fotograficas', models.JSONField(default=dict, null=True)),
                ('estado', models.CharField(max_length=40)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.IntegerField()),
                ('paquete', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='autenticacion.venta')),
            ],
        ),
    ]
