# Generated by Django 6.0.2 on 2026-03-24 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paqueteturistico',
            name='agencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_agencia', to='autenticacion.agencia', verbose_name='Agencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paqueteturistico',
            name='rating',
            field=models.DecimalField(decimal_places=100, default=0, max_digits=100),
        ),
    ]
