# Generated by Django 6.0.2 on 2026-03-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_add_agencia_to_paqueteturistico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paqueteturistico',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
