# Generated by Django 6.0.2 on 2026-04-07 04:58

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_add_foto_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
