# Generated by Django 6.0.2 on 2026-04-07 14:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_add_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='red_social',
        ),
        migrations.AddField(
            model_name='agencia',
            name='informacion_contacto',
            field=models.JSONField(blank=True, default=dict, help_text="Diccionario de redes sociales: {'instagram': 'url', 'facebook': 'url', 'whatsapp': 'numero'}", null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='rnt_registrado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='informacion_contacto',
            field=models.JSONField(blank=True, default=dict, help_text="Diccionario de redes sociales: {'instagram': 'url', 'facebook': 'url', 'whatsapp': 'numero'}", null=True),
        ),
        migrations.AddField(
            model_name='turista',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='logotipo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
