# Generated by Django 6.0.2 on 2026-03-14 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('caracteristicas', models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='logitid',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('duracion_horas', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=100, max_digits=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_riesgo', models.IntegerField()),
                ('caracteristicas', models.JSONField(blank=True, default=dict, null=True)),
                ('imagenes', models.JSONField(default=dict, null=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencia_paquete', to='autenticacion.agencia')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('sku', models.CharField(max_length=150)),
                ('caracterisitcas', models.JSONField(blank=True, default=dict)),
                ('imagenes', models.JSONField(default=dict, null=True)),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('disponible', models.BooleanField()),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_categorias', to='autenticacion.categorias')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_proveedor', to='autenticacion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_carrito', to='autenticacion.carrito')),
                ('paquetes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_paquetes', to='autenticacion.paquetes')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_productos', to='autenticacion.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorito_usuario', to=settings.AUTH_USER_MODEL)),
                ('paquetes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorito_paquetes', to='autenticacion.paquetes')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorito_productos', to='autenticacion.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('fotograficas', models.JSONField(default=dict, null=True)),
                ('estado', models.CharField(max_length=40)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.IntegerField()),
                ('paquete', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='autenticacion.venta')),
            ],
        ),
    ]
