# Generated by Django 6.0.2 on 2026-03-25 01:33

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_paqueteturistico_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='caracterisitcas',
            new_name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='productos',
            name='tipo_catalogo',
            field=models.CharField(choices=[('turistas', 'Turistas'), ('agencias', 'Agencias')], default='turistas', max_length=20),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('es_portada', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen_producto', to='autenticacion.productos')),
            ],
        ),
    ]
