# Generated by Django 6.0.2 on 2026-04-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_remove_agencia_red_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='novedades_turistas',
            field=models.JSONField(blank=True, default=list, help_text='Almacena el listado de viajeros y sus novedades registradas en el checkout en formato JSON.', null=True),
        ),
    ]
