# Generated by Django 6.0.2 on 2026-03-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_categoria_categorias_estados_turista_and_more'),
        ('autenticacion', '0004_categorias_estados_alter_proveedor_latitud_and_more'),
    ]

    operations = [
    ]
