# Generated by Django 6.0.2 on 2026-03-25 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_rename_caracterisitcas_productos_caracteristicas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=100, verbose_name='Grupo de Categoría')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Subcategoría')),
            ],
            options={
                'verbose_name': 'Categoría de Paquete',
                'verbose_name_plural': 'Categorías de Paquetes',
                'ordering': ['grupo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='paqueteturistico',
            name='categoria_paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes', to='autenticacion.categoriapaquete', verbose_name='Categoría del Tour'),
        ),
    ]
