# Generated by Django 6.0.2 on 2026-03-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_merge_20260319_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paquetes',
        ),
    ]
