# Generated by Django 6.0.2 on 2026-04-08 18:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_venta_novedades_turistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='turista',
            name='foto_portada',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
