# Generated by Django 6.0.2 on 2026-03-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_categoriapaquete_paqueteturistico_categoria_paquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_venta',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='items',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paqueteturistico',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
