# Generated by Django 6.0.2 on 2026-04-09 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_venta_novedades_turistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='fecha_reserva',
            field=models.DateField(blank=True, help_text='Fecha elegida por el turista para realizar el paquete (solo aplica a paquetes).', null=True, verbose_name='Fecha de Reserva'),
        ),
        migrations.AddField(
            model_name='paqueteturistico',
            name='fecha_realizacion',
            field=models.DateField(blank=True, help_text='Si se establece, el paquete es Fijo. Si está vacío, es Flexible.', null=True, verbose_name='Fecha de Realización'),
        ),
        migrations.AddField(
            model_name='paqueteturistico',
            name='tipo_paquete',
            field=models.CharField(choices=[('fijo', 'Fijo'), ('flexible', 'Flexible')], default='flexible', max_length=10, verbose_name='Tipo de Paquete'),
        ),
        migrations.CreateModel(
            name='ReservaFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Realización')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Personas')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_fecha', to='autenticacion.paqueteturistico', verbose_name='Paquete Turístico')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_fecha_venta', to='autenticacion.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Reserva por Fecha',
                'verbose_name_plural': 'Reservas por Fecha',
            },
        ),
    ]
