# Generated by Django 6.0.2 on 2026-03-26 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0006_alter_detalles_venta_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='paquetes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorito_paquetes', to='autenticacion.paqueteturistico'),
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorito_productos', to='autenticacion.productos'),
        ),
        migrations.AlterField(
            model_name='items',
            name='paquetes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_paquetes', to='autenticacion.paqueteturistico'),
        ),
        migrations.AlterField(
            model_name='items',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_productos', to='autenticacion.productos'),
        ),
    ]
