# Generated by Django 6.0.2 on 2026-04-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0006_items_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles_venta',
            name='estado',
            field=models.CharField(default='Pendiente de Empaque', max_length=40, verbose_name='Estado del Item'),
        ),
    ]
