# Generated by Django 6.0.2 on 2026-04-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0007_detalles_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
