# Generated by Django 6.0.2 on 2026-04-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0007_alter_favoritos_paquetes_alter_favoritos_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='red_social',
        ),
        migrations.AddField(
            model_name='agencia',
            name='informacion_contacto',
            field=models.JSONField(blank=True, default=dict, help_text="Diccionario de redes sociales: {'instagram': 'url', 'facebook': 'url', 'whatsapp': 'numero'}", null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='logitud',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
