# Generated by Django 6.0.2 on 2026-04-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0006_turista_foto_portada'),
        ('autenticacion', '0008_items_cantidad'),
    ]

    operations = [
    ]
