# Generated by Django 6.0.2 on 2026-04-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0009_merge_0006_turista_foto_portada_0008_items_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='numero_telefonico',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='numero_telefonico',
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_telefonico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
