# Generated by Django 6.0.2 on 2026-04-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0009_foto_perfil_cloudinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='rnt_registrado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
