# Generated by Django 6.0.2 on 2026-04-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0010_remove_agencia_numero_telefonico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='numero_telefonico',
        ),
        migrations.AddField(
            model_name='agencia',
            name='numero_telefonico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numero_telefonico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='turista',
            name='numero_telefonico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
