# Generated by Django 6.0.2 on 2026-04-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0010_agencia_rnt_registrado_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='informacion_contacto',
            field=models.JSONField(blank=True, default=dict, help_text="Diccionario de redes sociales: {'instagram': 'url', 'facebook': 'url', 'whatsapp': 'numero'}", null=True),
        ),
    ]
