# Generated by Django 6.0.2 on 2026-04-12 17:21

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0011_remove_usuario_numero_telefonico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='autenticacion.detalles_venta')),
            ],
            options={
                'verbose_name': 'Calificación de Experiencia',
                'verbose_name_plural': 'Calificaciones de Experiencias',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='autenticacion.detalles_venta')),
            ],
            options={
                'verbose_name': 'Evidencia de Experiencia',
                'verbose_name_plural': 'Evidencias de Experiencias',
            },
        ),
    ]
