# Generated by Django 6.0.2 on 2026-04-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0011_proveedor_descripcion_proveedor_horario_atencion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='informacion_contacto',
        ),
        migrations.RemoveField(
            model_name='agencia',
            name='rnt_registrado_at',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='horario_atencion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='informacion_contacto',
        ),
        migrations.RemoveField(
            model_name='turista',
            name='foto_perfil',
        ),
        migrations.AddField(
            model_name='agencia',
            name='red_social',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='logotipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
