# Generated by Django 6.0.2 on 2026-04-25 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0012_experienciacalificacion_experienciaevidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(max_length=50)),
                ('datos_bancarios', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Completado', 'Completado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('referencia', models.CharField(max_length=50, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
            },
        ),
    ]
