# Generated by Django 6.0.2 on 2026-07-10 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0012_experienciacalificacion_experienciaevidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(max_length=50)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('cuenta', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('titular', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Retiro',
                'verbose_name_plural': 'Solicitudes de Retiro',
            },
        ),
    ]
