# Generated by Django 6.0.2 on 2026-10-06 18:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0013_solicitudretiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstadoRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anterior', models.CharField(max_length=50)),
                ('nuevo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntentosCredenciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=64, unique=True)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('intentos', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='clave_operacion',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Simulado', 'Simulado'), ('Fallido', 'Fallido'), ('Reembolsado', 'Reembolsado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='huella_operacion',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='venta',
            name='moneda',
            field=models.CharField(default='COP', max_length=3),
        ),
        migrations.AddField(
            model_name='venta',
            name='vence_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('usuario', 'clave_operacion'), name='venta_operacion_unica'),
        ),
        migrations.AddField(
            model_name='cambioestadoretiro',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cambioestadoretiro',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios', to='autenticacion.solicitudretiro'),
        ),
    ]
