# Generated by Django 6.0.2 on 2026-10-06 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


def referencias_unicas(apps, schema_editor):
    Venta = apps.get_model('autenticacion', 'Venta')
    for pk in Venta.objects.using(schema_editor.connection.alias).values_list('pk', flat=True).iterator():
        Venta.objects.using(schema_editor.connection.alias).filter(pk=pk).update(referencia_pago=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0014_cambioestadoretiro_intentoscredenciales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ambiente_pago',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='venta',
            name='referencia_pago',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(referencias_unicas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='venta',
            name='referencia_pago',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Simulado', 'Simulado'), ('Fallido', 'Fallido'), ('Reembolsado', 'Reembolsado'), ('Revision', 'Revision')], default='Pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='EventoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('transaccion', models.CharField(max_length=100)),
                ('ambiente', models.CharField(max_length=4)),
                ('estado', models.CharField(max_length=20)),
                ('importe_centavos', models.BigIntegerField()),
                ('moneda', models.CharField(max_length=3)),
                ('resultado', models.CharField(max_length=30)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_pago', to='autenticacion.venta')),
            ],
        ),
    ]
