FROM node:20-alpine as build-stage

WORKDIR /frontend_project

COPY package*.json ./

RUN npm run build


FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /frontend_project/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g","daemon off;"]